server:
  port: 8080
  context-path: /ted
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ted
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true